"""empty message

Revision ID: 1b7672f13cc9
Revises: c2164afe5758
Create Date: 2022-09-07 18:15:23.159469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7672f13cc9'
down_revision = 'c2164afe5758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('prepared_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'prepared_date')
    # ### end Alembic commands ###
