"""empty message

Revision ID: 5519307aa20d
Revises: ddacf5208d07
Create Date: 2022-09-15 11:23:25.801520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5519307aa20d'
down_revision = 'ddacf5208d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('specialties', sa.String(length=50), nullable=True))
    op.add_column('staff', sa.Column('experience', sa.String(length=10), nullable=True))
    op.add_column('staff', sa.Column('about', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'about')
    op.drop_column('staff', 'experience')
    op.drop_column('staff', 'specialties')
    # ### end Alembic commands ###
