"""empty message

Revision ID: bebb965fe707
Revises: d381cfb58c05
Create Date: 2022-09-15 23:18:59.267947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebb965fe707'
down_revision = 'd381cfb58c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnose',
    sa.Column('diagnose_id', sa.Integer(), nullable=False),
    sa.Column('diagnose', sa.String(length=1000), nullable=False),
    sa.Column('advice', sa.String(length=1000), nullable=True),
    sa.Column('medicine', sa.String(length=1000), nullable=True),
    sa.Column('dosage', sa.String(length=1000), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointment_id'], ),
    sa.PrimaryKeyConstraint('diagnose_id')
    )
    op.create_table('visit',
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('weigth', sa.Integer(), nullable=True),
    sa.Column('temp', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointment_id'], ),
    sa.PrimaryKeyConstraint('visit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit')
    op.drop_table('diagnose')
    # ### end Alembic commands ###
