"""empty message

Revision ID: c2164afe5758
Revises: 
Create Date: 2022-09-07 17:33:26.765076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2164afe5758'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance',
    sa.Column('insurance_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('insurance_id')
    )
    op.create_table('personal',
    sa.Column('personal_info_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('street', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=5), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('profile_img', sa.String(length=255), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('personal_info_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_personal_token'), 'personal', ['token'], unique=True)
    op.create_table('staff',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('started_date', sa.DateTime(), nullable=False),
    sa.Column('personal_info_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personal_info_id'], ['personal.personal_info_id'], ),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_table('user',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('personal_info_id', sa.Integer(), nullable=False),
    sa.Column('insurance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['insurance_id'], ['insurance.insurance_id'], ),
    sa.ForeignKeyConstraint(['personal_info_id'], ['personal.personal_info_id'], ),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('invoice',
    sa.Column('invoce_id', sa.Integer(), nullable=False),
    sa.Column('room_charge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('medicine_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('doctor_charge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('other_charge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('insurance_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['insurance_id'], ['insurance.insurance_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.patient_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('invoce_id')
    )
    op.create_table('qualificaiton',
    sa.Column('qualificaiton_id', sa.Integer(), nullable=False),
    sa.Column('qualificaiton_type', sa.String(length=50), nullable=False),
    sa.Column('issued_date', sa.DateTime(), nullable=True),
    sa.Column('expire_date', sa.DateTime(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('qualificaiton_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qualificaiton')
    op.drop_table('invoice')
    op.drop_table('user')
    op.drop_table('staff')
    op.drop_index(op.f('ix_personal_token'), table_name='personal')
    op.drop_table('personal')
    op.drop_table('insurance')
    # ### end Alembic commands ###
