"""empty message

Revision ID: d281c2fbf9f6
Revises: d3348727e2c2
Create Date: 2022-09-10 00:20:33.169112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd281c2fbf9f6'
down_revision = 'd3348727e2c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal', sa.Column('username', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'personal', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personal', type_='unique')
    op.drop_column('personal', 'username')
    # ### end Alembic commands ###
