"""empty message

Revision ID: d3348727e2c2
Revises: 
Create Date: 2022-09-08 21:28:42.175340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3348727e2c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('time_slot', sa.Time(), nullable=False),
    sa.Column('appointment_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=400), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['staff.staff_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.patient_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    # ### end Alembic commands ###
