"""empty message

Revision ID: d381cfb58c05
Revises: 5519307aa20d
Create Date: 2022-09-15 15:05:29.780066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd381cfb58c05'
down_revision = '5519307aa20d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('appointment_patient_id_fkey', 'appointment', type_='foreignkey')
    op.create_foreign_key(None, 'appointment', 'personal', ['patient_id'], ['personal_info_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.create_foreign_key('appointment_patient_id_fkey', 'appointment', 'user', ['patient_id'], ['patient_id'])
    # ### end Alembic commands ###
