"""empty message

Revision ID: ddacf5208d07
Revises: ee1de302cff6
Create Date: 2022-09-14 18:53:22.011904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddacf5208d07'
down_revision = 'ee1de302cff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'time_slot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('time_slot', postgresql.TIME(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
