"""empty message

Revision ID: ee1de302cff6
Revises: 002a66e564b4
Create Date: 2022-09-10 00:45:56.112261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1de302cff6'
down_revision = '002a66e564b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal', sa.Column('state', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal', 'state')
    # ### end Alembic commands ###
