"""empty message

Revision ID: fa34b3b4e942
Revises: 
Create Date: 2022-09-20 22:06:25.641392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa34b3b4e942'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=400), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['staff.staff_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['personal.personal_info_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('diagnose',
    sa.Column('diagnose_id', sa.Integer(), nullable=False),
    sa.Column('diagnose', sa.String(length=1000), nullable=False),
    sa.Column('advice', sa.String(length=1000), nullable=True),
    sa.Column('medicine', sa.String(length=1000), nullable=True),
    sa.Column('dosage', sa.String(length=1000), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointment_id'], ),
    sa.PrimaryKeyConstraint('diagnose_id')
    )
    op.create_table('visit',
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weigth', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointment_id'], ),
    sa.PrimaryKeyConstraint('visit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit')
    op.drop_table('diagnose')
    op.drop_table('appointment')
    # ### end Alembic commands ###
